Update patch set 1
Patch Set 1:

frameworks/opt/net/ims/src/java/com/android/ims/ImsUt.java:328: error: method updateCallBarring in interface IImsUt cannot be applied to given types;
                int id = miUt.updateCallBarring(cbType, enable, barrList);
                             ^
  required: int,int,String[]
  found: int,boolean,String[]
  reason: actual argument boolean cannot be converted to int by method invocation conversion
Note: frameworks/opt/net/ims/src/java/com/android/ims/ImsManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: frameworks/opt/net/ims/src/java/com/android/ims/ImsUt.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

Patch-set: 1
Reviewer: BobZhome <1743@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0