Update patch set 1
Patch Set 1:

frameworks/opt/telephony/src/java/com/android/internal/telephony/imsphone/ImsPhone.java:854: error: method updateCallBarring in interface ImsUtInterface cannot be applied to given types;
            ut.updateCallBarring(getCBTypeFromFacility(facility), lockState, resp, null);
              ^
  required: int,int,Message,String[]
  found: int,boolean,Message,<null>
  reason: actual argument boolean cannot be converted to int by method invocation conversion
frameworks/opt/telephony/src/java/com/android/internal/telephony/imsphone/ImsPhoneMmiCode.java:1146: error: method updateCallBarring in interface ImsUtInterface cannot be applied to given types;
            .updateCallBarring(ImsUtInterface.CB_BS_MT,
            ^
  required: int,int,Message,String[]
  found: int,boolean,Message,String[]
  reason: actual argument boolean cannot be converted to int by method invocation conversion
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

Patch-set: 1
Reviewer: Ray W <12155@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>
Label: Verified=0